apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sp-lr-pipeline-run-
  name: sp-lr-pipeline-run-1
spec:
  params:
    - name: sp-lr-repo-url
      value: 'https://github.com/parkarteam/sp-lr-classifier.git'
    - name: PROJECT
      value: odh-dev   
  pipelineRef:
    name: sp-lr-pipeline
  resources:
    - name: app-image
      resourceRef:
        name: sp-lr-classifier-image
  workspaces:
    - name: shared-ws
      persistentVolumeClaim:
        claimName: lr-source
