apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: lr-sklearn
spec:
  annotations:
    seldon.io/executor: "true"
  name: lr-sp
  predictors:
  - componentSpecs:
    - spec:
       containers:
       - name: classifier
         image: image-registry.openshift-image-registry.svc:5000/odh-dev/sp-lr-classifier-image:latest
    graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://frauddetection/uploaded/lrmodel
      envSecretRefName: seldon-init-container-secret
      name: classifier
      parameters:
        - name: method
          type: STRING
          value: predict_proba
    name: default
    replicas: 1
