--- 
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: sklearnserver-rest
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 1.2.3
      from:
        kind: DockerImage
        name: 'seldonio/sklearnserver_rest:1.2.3'
                  