apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sp-classifier-pipeline
spec:
  workspaces:
      - name: shared-ws
      - name: combiner-ws
  params:
  - name: sp-lr-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-lr-classifier.git'  
  - name: sp-path-context
    type: string
    description: The location of the path to run build from.   
    default: classifier    
  - name: combiner-path-context
    type: string
    description: The location of the path to run build from.   
    default: combiner    
  - name: transformer-path-context
    type: string
    description: The location of the path to run build from.   
    default: transformer  
  - name: PROJECT
    type: string
    description: The namespace of the opensift.   
    default: odh-dev        
  - name: sp-rf-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-rf-classifier.git'                   
  - name: sp-gb-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-gb-classifier.git'                             
  - name: sp-gmm-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-gmm-classifier.git'                   
  - name: sp-dt-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-dt-classifier.git'                   
  - name: sp-combiner-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-combiner.git'                   
  - name: sp-transformer-repo-url
    type: string
    description: The git repository URL to clone from.
    default: 'https://github.com/parkarteam/sp-transformer.git'                   
  resources:
  - name: lr-app-image
    type: image
  - name: rf-app-image
    type: image
  - name: gb-app-image
    type: image
  - name: gmm-app-image
    type: image
  - name: dt-app-image
    type: image
  - name: combiner-app-image
    type: image
  - name: transformer-app-image
    type: image
  tasks:

    # Main start

  - name: fetch-lr-repo
    runAfter:
      - generate-transformer-image-push
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.sp-lr-repo-url)
    - name: deleteExisting
      value: "true"
  - name: generate-lr-image-push
    runAfter: 
      - fetch-lr-repo 
    resources:
      outputs:
      - name: image
        resource:  lr-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.sp-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: shared-ws      
    # Main end
  
  # Second start
  - name: fetch-rf-repo
    runAfter: 
      - generate-lr-image-push  
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.sp-rf-repo-url)
    - name: deleteExisting
      value: "true" 
  - name: generate-rf-image-push
    runAfter: 
      - fetch-rf-repo 
    resources:
      outputs:
      - name: image
        resource:  rf-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.sp-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: shared-ws      
  - name: fetch-gb-repo
    runAfter: 
      - generate-rf-image-push  
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.sp-gb-repo-url)
    - name: deleteExisting
      value: "true" 
  - name: generate-gb-image-push
    runAfter: 
      - fetch-gb-repo 
    resources:
      outputs:
      - name: image
        resource:  gb-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.sp-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: shared-ws      
  - name: fetch-gmm-repo
    runAfter: 
      - generate-gb-image-push  
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.sp-gmm-repo-url)
    - name: deleteExisting
      value: "true" 
  - name: generate-gmm-image-push
    runAfter: 
      - fetch-gmm-repo 
    resources:
      outputs:
      - name: image
        resource:  gmm-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.sp-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: shared-ws      
  - name: fetch-dt-repo
    runAfter: 
      - generate-gmm-image-push  
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.sp-dt-repo-url)
    - name: deleteExisting
      value: "true" 
  - name: generate-dt-image-push
    runAfter: 
      - fetch-dt-repo 
    resources:
      outputs:
      - name: image
        resource:  dt-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.sp-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: shared-ws      
  - name: fetch-combiner-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    # runAfter: 
    #   - generate-lr-image-push      
    workspaces:
    - name: output
      workspace: combiner-ws
    params:
    - name: url
      value: $(params.sp-combiner-repo-url)
    - name: deleteExisting
      value: "true"
  - name: generate-combiner-image-push
    runAfter: 
      - fetch-combiner-repo 
    resources:
      outputs:
      - name: image
        resource:  combiner-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.combiner-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: combiner-ws     
  # Second end
  
  # Sedon start
  - name: fetch-transformer-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter: 
      - generate-combiner-image-push
    workspaces:
    - name: output
      workspace: combiner-ws
    params:
    - name: url
      value: $(params.sp-transformer-repo-url)
    - name: deleteExisting
      value: "true"
  - name: generate-transformer-image-push
    runAfter: 
      - fetch-transformer-repo 
    resources:
      outputs:
      - name: image
        resource:  transformer-app-image
    taskRef:
      name: bud-push
    params: 
    - name: PATH_CONTEXT
      value: $(params.transformer-path-context) 
    - name: PROJECT
      value: $(params.PROJECT) 
    workspaces:
      - name: source
        workspace: combiner-ws      
  
  # Seldon end 

        